### PR TITLE
add script to produce binaries

### PR DESCRIPTION
**Pull request by akisblack**

### CODE REVIEW

**Comment by MMK21Hub** [comment]
Just wondering: why has the `package-lock.json` been removed?

**Comment by akisblack** [comment]
> Just wondering: why has the `package-lock.json` been removed?

It has been replaced by a `pnpm-lock.yaml` which is the lockfile for the pnpm package manager. Since both me and Odyssey use it for our shared projects it would also be nice to have it here as well

**Comment by akisblack** [comment]
oh wait i forgot to un-.gitignore pnpm lockfiles

**Comment by Odyssey346** [comment]
bruh, I want es6.

**Comment by akisblack** [comment]
development and compilation from ts to js is still done using es2022 features, the only thing that is using cjs is the system binaries

**Pull request merged**
